apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hernandez-juiceshop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/carloshzoghbi/cicd-demo.git'
    path: app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hernandez
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
